# Generated by Django 3.1.3 on 2020-11-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listofmovies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(blank=True, help_text='Choose a genre of the movie', null=True, to='listofmovies.Genre'),
        ),
    ]
