# Generated by Django 3.1.3 on 2020-11-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listofmovies', '0004_movie_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='big_photo',
            field=models.ImageField(null=True, upload_to='listofmovies/'),
        ),
    ]
