# Generated by Django 3.1.3 on 2020-11-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listofmovies', '0005_movie_big_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='image',
            field=models.ImageField(null=True, upload_to='genres/'),
        ),
    ]
